In [1]:
;# Import all libraries needed for the tutorial
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Enable inline plotting
%matplotlib inline

In [2]:
df = pd.read_csv('inspections.csv')
df.head(10)

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_name,facility_state,facility_zip,grade,owner_id,owner_name,pe_description,program_element_pe,program_name,program_status,record_id,score,serial_number,service_code,service_description
0,2017-05-09,EE0000593,17660 CHATSWORTH ST,GRANADA HILLS,FA0175397,HOVIK'S FAMOUS MEAT & DELI,CA,91344,A,OW0181955,JOHN'S FAMOUS MEAT & DELI INC.,"FOOD MKT RETAIL (25-1,999 SF) HIGH RISK",1612,HOVIK'S FAMOUS MEAT & DELI,ACTIVE,PR0168541,98,DAHDRUQZO,1,ROUTINE INSPECTION
1,2017-04-10,EE0000126,3615 PACIFIC COAST HWY,TORRANCE,FA0242138,SHAKEY'S PIZZA,CA,90505,A,OW0237843,"SCO, LLC",RESTAURANT (61-150) SEATS HIGH RISK,1638,SHAKEY'S PIZZA,ACTIVE,PR0190290,94,DAL3SBUE0,1,ROUTINE INSPECTION
2,2017-04-04,EE0000593,17515 CHATSWORTH ST,GRANADA HILLS,FA0007801,BAITH AL HALAL,CA,91344,A,OW0031150,SABIR MOHAMMAD SHAHID,"FOOD MKT RETAIL (25-1,999 SF) HIGH RISK",1612,BAITH AL HALAL,INACTIVE,PR0036723,95,DAL2PIKJU,1,ROUTINE INSPECTION
3,2017-08-15,EE0000971,44455 VALLEY CENTRAL WAY,LANCASTER,FA0013858,FOOD 4 LESS #306,CA,93536,A,OW0012108,"FOOD 4 LESS, INC.",RESTAURANT (0-30) SEATS HIGH RISK,1632,FOOD 4 LESS DELI/BAKERY#306,ACTIVE,PR0039905,98,DA0ZMAJXZ,1,ROUTINE INSPECTION
4,2016-09-26,EE0000145,11700 SOUTH ST,ARTESIA,FA0179671,PHO LITTLE SAIGON,CA,90701,A,OW0185167,PHO SOUTH ST INC,RESTAURANT (61-150) SEATS HIGH RISK,1638,PHO LITTLE SAIGON,ACTIVE,PR0173311,96,DA41DBXA2,1,ROUTINE INSPECTION
5,2016-05-11,EE0000720,1309 S HOOVER ST,LOS ANGELES,FA0179745,HAPPY TACOS TO GO,CA,90006-4903,A,OW0185239,MAT L. MORA,RESTAURANT (0-30) SEATS HIGH RISK,1632,HAPPY TACOS TO GO,INACTIVE,PR0173403,96,DAURQTTVR,1,ROUTINE INSPECTION
6,2017-02-28,EE0000741,4959 PATATA ST,CUDAHY,FA0012590,EL POTRERO CLUB,CA,90201,B,OW0036634,"TSAY, SHYR JIN",RESTAURANT (151 + ) SEATS HIGH RISK,1641,EL POTRERO CLUB,ACTIVE,PR0041708,87,DAUNXDSVP,1,ROUTINE INSPECTION
7,2016-11-03,EE0000721,524 S MAIN ST,LOS ANGELES,FA0051633,THE NICKEL DINER,CA,90013,A,OW0004308,"BELLE DU JOUR, INC",RESTAURANT (31-60) SEATS HIGH RISK,1635,THE NICKEL DINER,ACTIVE,PR0000202,96,DAFLSXKZ2,1,ROUTINE INSPECTION
8,2016-02-17,EE0000742,333 W BONITA AVE,CLAREMONT,FA0062434,FULL OF LIFE BAKERY,CA,91711,A,OW0003740,"BAIK, SEOUNG SEOK",RESTAURANT (0-30) SEATS MODERATE RISK,1631,FULL OF LIFE BAKERY,INACTIVE,PR0017727,96,DARSNHKM0,1,ROUTINE INSPECTION
9,2017-04-18,EE0000745,11954 E CARSON ST,HAWAIIAN GARDENS,FA0007900,CARSON LIQUOR,CA,90716,A,OW0019875,"KOO, HE OK ET AL","FOOD MKT RETAIL (25-1,999 SF) LOW RISK",1610,CARSON LIQUOR,ACTIVE,PR0024704,94,DAPAA2DQ3,1,ROUTINE INSPECTION

In [3]:
df.grade.value_counts()

A    181278
B      9379
C       682
         32
Name: grade, dtype: int64

In [4]:
df.columns

Index(['activity_date', 'employee_id', 'facility_address', 'facility_city',
       'facility_id', 'facility_name', 'facility_state', 'facility_zip',
       'grade', 'owner_id', 'owner_name', 'pe_description',
       'program_element_pe', 'program_name', 'program_status', 'record_id',
       'score', 'serial_number', 'service_code', 'service_description'],
      dtype='object')

In [5]:
df['activity_date'].max()

'2017-12-29'

In [6]:
df['activity_date'].min()

'2015-07-01'

In [7]:
df.groupby('facility_zip').nunique()

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_name,facility_state,facility_zip,grade,owner_id,owner_name,pe_description,program_element_pe,program_name,program_status,record_id,score,serial_number,service_code,service_description
facility_zip,,,,,,,,,,,,,,,,,,,,
90001,318,7,222,2,237,232,1,1,3,235,234,14,14,242,2,248,23,861,2,2
90001-1002,4,1,1,1,2,2,1,1,1,2,2,1,1,2,2,2,3,4,1,1
90001-1127,9,1,2,1,2,2,1,1,1,2,2,1,1,2,1,2,7,12,1,1
90001-1222,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-1312,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-1644,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-1646,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,1,1
90001-1710,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-1771,7,1,3,1,3,3,1,1,1,3,3,3,3,3,1,3,4,7,1,1
90001-1830,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,1
90001-1966,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,5,1,1
90001-2128,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,5,1,1
90001-2422,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-2550,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-2555,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,1
90001-2656,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-2714,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,5,1,1
90001-2733,7,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,7,1,1
90001-3317,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-3499,7,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,7,1,1
90001-3524,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90001-3826,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,2,1,1
90001-3918,3,1,2,1,2,2,1,1,1,2,2,2,2,2,2,2,3,3,1,1
90002,128,6,54,1,60,58,1,1,3,60,60,12,12,61,2,63,16,191,2,2
90002-1112,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,1,1
90002-1331,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,5,1,1
90002-1334,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,2,1,1
90002-1637,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
90002-1738,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1
90002-1744,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93536-6533,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
93536-7619,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,5,1,1
93536-8342,8,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,8,1,1
93536-8501,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
93543,70,3,23,2,26,26,1,1,3,25,25,10,10,27,2,28,14,110,2,2
93543-3034,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,1,1
93543-3040,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
93544,6,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,6,1,1
93550,284,6,188,1,198,192,1,1,3,193,189,15,15,208,2,213,23,767,2,2
93550-1202,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,1,1
93550-2112,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,1,1
93550-4711,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,5,1,1
93550-4914,7,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,7,7,1,1
93550-7401,8,1,1,1,2,2,1,1,1,2,2,2,2,2,1,2,8,16,1,1
93551,324,4,215,3,221,207,1,1,3,213,213,15,15,223,2,238,23,899,2,2
93551-3031,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,1,1
93551-3101,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1
93551-3701,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,1,1
93551-3713,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,1,1
93551-4208,6,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,5,6,1,1
93551-4248,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,1,1
93551-4564,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
93551-5729,8,1,1,1,1,1,1,1,1,1,1,3,3,3,1,3,8,12,1,1
93552,137,4,58,2,70,68,1,1,3,61,61,14,14,78,2,82,17,285,2,2
93552-2903,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
93552-3109,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,1
93552-4483,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,4,1,1
93553,14,2,6,1,6,6,1,1,1,6,6,4,4,6,2,6,8,17,1,1
93591,45,2,19,1,20,19,1,1,3,20,20,11,11,21,2,22,16,81,2,2
93591-3342,3,1,1,1,1,1,1,1,1,1,1,2,2,1,1,1,3,3,1,1

In [8]:

df['short_zip'] = df['facility_zip'].str[0:5]
#df['short_zip'] = df['facility_zip'][0:5]
df[['facility_zip', 'short_zip']]

       facility_zip short_zip
0             91344     91344
1             90505     90505
2             91344     91344
3             93536     93536
4             90701     90701
5        90006-4903     90006
6             90201     90201
7             90013     90013
8             91711     91711
9             90716     90716
10            90015     90015
11            90640     90640
12            90745     90745
13            91602     91602
14            90079     90079
15            90255     90255
16            91303     91303
17            91324     91324
18            91723     91723
19            91744     91744
20            93551     93551
21            90046     90046
22            90703     90703
23            90025     90025
24            91201     91201
25            90638     90638
26       90701-3804     90701
27            90277     90277
28            90704     90704
29            91608     91608
...             ...       ...
191341        91342     91342
191342        91311     91311
191343        90012     90012
191344        90015     90015
191345        91344     91344
191346        91351     91351
191347        90064     90064
191348        90603     90603
191349        90058     90058
191350        93535     93535
191351        90045     90045
191352        90291     90291
191353        90280     90280
191354        90502     90502
191355        90043     90043
191356        91789     91789
191357   91770-3367     91770
191358        90606     90606
191359        90210     90210
191360        91733     91733
191361        90069     90069
191362        90305     90305
191363        90042     90042
191364        91423     91423
191365        90602     90602
191366        90005     90005
191367        90249     90249
191368        90701     90701
191369        90731     90731
191370        90007     90007

[191371 rows x 2 columns]

### look at different percentiles (inspection date nunique) to find which zip codes have large/small number of entries

In [9]:
df.groupby('short_zip').nunique().head()

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_name,facility_state,facility_zip,grade,owner_id,...,pe_description,program_element_pe,program_name,program_status,record_id,score,serial_number,service_code,service_description,short_zip
short_zip,,,,,,,,,,,,,,,,,,,,,
90001,334,9,239,2,264,254,1,23,3,260,...,14,14,264,2,275,24,935,2,2,1
90002,140,6,58,1,68,65,1,9,3,68,...,12,12,68,2,71,17,211,2,2,1
90003,341,9,247,1,268,258,1,35,3,260,...,13,13,273,2,284,26,910,2,2,1
90004,404,11,234,1,271,264,1,22,3,263,...,17,17,263,2,274,24,1144,2,2,1
90005,422,10,258,1,296,286,1,22,4,291,...,17,17,297,2,309,31,1343,2,2,1

###

In [10]:
df.groupby('short_zip').count()['activity_date'].max()

2215

In [11]:
df.shape

(191371, 21)

In [12]:
df.score.min()

54

In [13]:
# df.loc(df.score == 54)
df[df.score == 54]

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_name,facility_state,facility_zip,grade,owner_id,...,pe_description,program_element_pe,program_name,program_status,record_id,score,serial_number,service_code,service_description,short_zip
134037,2017-07-11,EE0000829,888 E DOMINGUEZ ST E,CARSON,FA0007895,CARSON BUFFET,CA,90746,,OW0006281,...,RESTAURANT (151 + ) SEATS HIGH RISK,1641,CARSON BUFFET,INACTIVE,PR0021633,54,DAREI9PD0,1,ROUTINE INSPECTION,90746

In [14]:
df.groupby('program_status').count()

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_name,facility_state,facility_zip,grade,owner_id,owner_name,pe_description,program_element_pe,program_name,record_id,score,serial_number,service_code,service_description,short_zip
program_status,,,,,,,,,,,,,,,,,,,,
ACTIVE,169477,169477,169477,169477,169477,169477,169477,169477,169477,169477,169477,169477,169477,169139,169477,169477,169477,169477,169477,169477
INACTIVE,21894,21894,21894,21894,21894,21894,21894,21894,21894,21894,21894,21894,21894,21830,21894,21894,21894,21894,21894,21894

In [15]:
actives = df[df['program_status'] == 'ACTIVE']

In [16]:
df.groupby('facility_name').count().head()

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_state,facility_zip,grade,owner_id,owner_name,pe_description,program_element_pe,program_name,program_status,record_id,score,serial_number,service_code,service_description,short_zip
facility_name,,,,,,,,,,,,,,,,,,,,
"""R"" KITCHEN",6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
#1 BUFFET,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
#1 CAFE,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#1 CHINESE FAST FOOD,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
#1 DELICIOUS DONUTS,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4

In [17]:
actives.groupby('program_name').count()

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_name,facility_state,facility_zip,grade,owner_id,owner_name,pe_description,program_element_pe,program_status,record_id,score,serial_number,service_code,service_description,short_zip
program_name,,,,,,,,,,,,,,,,,,,,
"""POP'S CHICKEN"" MEXICAN FOOD",7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
"""R"" KITCHEN",6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
# 245 BASE BOWLS,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
# 431 LOGE TERRACE BAR,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
# 953 TOP DECK DOGS,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
#1 BUFFET,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
#1 CAFE,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#1 CHINESE FAST FOOD,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
#1 DELICIOUS DONUTS,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
#1 DONUTS,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
#1 NOODLE HOUSE,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
#1. JUICY DUMPLING,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
#102 ALL INCLUSIVE (AYCE),5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#103 DODGER DOG TRADITIONAL,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#104 ALL INCLUSIVE (AYCE),5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#105 DODGER DOG TRADITIONAL,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#2 MOON BBQ,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
#204 CAMPY'S CORNER,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#205 MARKET PLACE HEALTHY PLATE,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
#208 CHICK N TOTS,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
#209 DODGER DOG TRADITIONAL,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#210 LA TAQUERIA,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
#222 ELYSIAN PARK GRILL,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
#223 DODGER DOGS TRADITIONAL,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
#240 DODGER DOG TRADITIONAL,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#241 DODGER DOGS TRADITIONAL,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#246 TROLLEY TREATS,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#247 BUD AND BURGERS,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
#248 DODGER DOG TRADITIONAL,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
#251 KINGS HAWAIIAN,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZION MARKET MEAT/SEAFOOD,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
ZION MARKET RETAIL,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
ZIP N LIQUOR,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
ZODIAC JUICEOLOGY AND APOTHECARY,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
ZOE'S SMOKE N SNACK SHOP,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ZOGO CHARBROIL BURGER,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
ZONE CLUB,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
ZONO SUSHI,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
ZOO GRILL KIOSK,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
ZOO PRODUCTION KITCHEN,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
ZOOMA SUSHI,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
ZOVK,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
ZOZOYA'S LIQUOR,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ZUBEDA'S MINI MARKET,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
ZUI XIANG YUAN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ZULEMA BAKERY,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
ZULEYICA'S JUICE BAR,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
ZULY'S 99 AND UP DISCOUNT,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
ZUMA CAFE,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
ZUMAYA'S,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
ZUMBA MANIA,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
ZUMBROTA,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
ZUMO ZUZHI BURRITO,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
ZUNIGA'S MARKET,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
ZUZU CHICKEN,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
ZWEET CAFE,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
ZWONNY KITCHEN INC,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
ZZAMONG,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
arCO AM PM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
v,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3

In [18]:
df.groupby('service_description').count()

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_name,facility_state,facility_zip,grade,owner_id,owner_name,pe_description,program_element_pe,program_name,program_status,record_id,score,serial_number,service_code,short_zip
service_description,,,,,,,,,,,,,,,,,,,,
OWNER INITIATED ROUTINE INSPECT.,2908,2908,2908,2908,2908,2908,2908,2908,2908,2908,2908,2908,2908,2900,2908,2908,2908,2908,2908,2908
ROUTINE INSPECTION,188463,188463,188463,188463,188463,188463,188463,188463,188463,188463,188463,188463,188463,188069,188463,188463,188463,188463,188463,188463

In [19]:
df.describe()

       program_element_pe          score   service_code
count       191371.000000  191371.000000  191371.000000
mean          1629.888980      93.753306       7.078246
std              9.391426       3.845518      48.932257
min           1610.000000      54.000000       1.000000
25%           1631.000000      91.000000       1.000000
50%           1632.000000      94.000000       1.000000
75%           1635.000000      97.000000       1.000000
max           1641.000000     100.000000     401.000000

In [20]:
# df['grade' == 'A']
df[df['grade'] == ' ']

,activity_date,employee_id,facility_address,facility_city,facility_id,facility_name,facility_state,facility_zip,grade,owner_id,...,pe_description,program_element_pe,program_name,program_status,record_id,score,serial_number,service_code,service_description,short_zip
766,2017-09-20,EE0000163,14021 S PIONEER BLVD,NORWALK,FA0177189,HIBACHI GRILL BUFFET,CA,90650,,OW0183147,...,RESTAURANT (151 + ) SEATS HIGH RISK,1641,HIBACHI GRILL BUFFET,ACTIVE,PR0170152,65,DAAJPSDX7,1,ROUTINE INSPECTION,90650
891,2017-02-07,EE0000821,745 E GARVEY AVE STE 101,MONTEREY PARK,FA0166263,PHO BANH MI CHE CALI,CA,91755-3068,,OW0129433,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,PHO BANH MI CHE CALI,ACTIVE,PR0156516,67,DAQOIVOGA,1,ROUTINE INSPECTION,91755
9002,2017-04-05,EE0000821,108 N GARFIELD AVE,MONTEREY PARK,FA0240496,EAST FUSION RESTAURANT,CA,91754,,OW0236578,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,EAST FUSION RESTAURANT,ACTIVE,PR0188528,62,DAUF1RDDI,1,ROUTINE INSPECTION,91754
11308,2016-09-21,EE0000854,3418 W 8TH ST,LOS ANGELES,FA0049645,STO. DOMINGO BAKERY,CA,90005,,OW0015350,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,STO. DOMINGO BAKERY,ACTIVE,PR0038369,65,DAABC7FCZ,1,ROUTINE INSPECTION,90005
14439,2015-09-10,EE0000882,2210 MARINE AVE STE J,GARDENA,FA0170261,FORTUNE CORNER CHINESE FOOD,CA,90249,,OW0178072,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,CHINESE FOOD,INACTIVE,PR0160724,66,DAXAEXIJS,1,ROUTINE INSPECTION,90249
20672,2017-08-24,EE0000829,21705 S MAIN ST,CARSON,FA0010110,BLUE LOTUS VIETNAMESE CUISINE,CA,90745,,OW0037883,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,BLUE LOTUS VIETNAMESE CUISINE,ACTIVE,PR0028461,58,DAG0GFTLU,1,ROUTINE INSPECTION,90745
25097,2017-12-13,EE0000182,12819 PENN ST,WHITTIER,FA0156077,LITTLE CHILDREN NUTRITION,CA,90602-1538,,OW0121337,...,"FOOD MKT RETAIL (25-1,999 SF) LOW RISK",1610,LITTLE CHILDREN NUTRITION,ACTIVE,PR0143537,57,DA6LLN6VL,1,ROUTINE INSPECTION,90602
39392,2017-02-22,EE0000735,24947 W PICO CANYON RD,STEVENSON RANCH,FA0175219,YAMATO RESTAURANT,CA,91381,,OW0181798,...,RESTAURANT (151 + ) SEATS HIGH RISK,1641,YAMATO RESTAURANT,ACTIVE,PR0168337,62,DABGIKVEJ,1,ROUTINE INSPECTION,91381
71731,2017-06-21,EE0000829,313 E CARSON ST,CARSON,FA0033740,SOL NIGHT CLUB,CA,90745,,OW0033411,...,RESTAURANT (61-150) SEATS LOW RISK,1636,SOL NIGHT CLUB,ACTIVE,PR0019420,67,DA0JQS1JM,1,ROUTINE INSPECTION,90745
75325,2017-04-26,EE0000747,2423 S AZUSA AVE,WEST COVINA,FA0024855,MIKI HOUSE,CA,91792,,OW0034945,...,RESTAURANT (31-60) SEATS HIGH RISK,1635,MIKI HOUSE,ACTIVE,PR0016973,67,DA0838774,1,ROUTINE INSPECTION,91792
95092,2017-08-28,EE0000145,19008 S PIONEER BLVD,CERRITOS,FA0046818,SAM WOO SEAFOOD BBQ REST,CA,90703,,OW0028343,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,SAM WOO SEAFOOD BBQ REST,ACTIVE,PR0028575,64,DAO157AK3,1,ROUTINE INSPECTION,90703
99230,2017-06-20,EE0000821,245 W VALLEY BLVD,ALHAMBRA,FA0007773,BACCALI CAFE & ROTISSERIE,CA,91801,,OW0007911,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,BACCALI CAFE & ROTISSERIE,ACTIVE,PR0038551,64,DAN0B0D5I,1,ROUTINE INSPECTION,91801
99679,2017-02-27,EE0000018,14426 S CRENSHAW BLVD STE D,GARDENA,FA0063992,ISLAND REGGAE KITCHEN,CA,90249,,OW0026157,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,ISLAND REGGAE KITCHEN,ACTIVE,PR0010237,67,DAFIPOCBC,1,ROUTINE INSPECTION,90249
107327,2015-10-06,EE0000742,18472 E COLIMA RD STE #100,ROWLAND HEIGHTS,FA0061238,EASTERN EXPRESS CAFE,CA,91748,,OW0010656,...,RESTAURANT (31-60) SEATS HIGH RISK,1635,EASTERN EXPRESS CAFE,INACTIVE,PR0006250,69,DAB7KNMC5,1,ROUTINE INSPECTION,91748
108062,2017-10-24,EE0000464,18331 SHERMAN WAY,RESEDA,FA0052013,THE GREAT WALL,CA,91335,,OW0007549,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,THE GREAT WALL,ACTIVE,PR0024041,63,DAFGHDNYD,1,ROUTINE INSPECTION,91335
110228,2017-08-03,EE0000953,4135 S CENTINELA AVE,LOS ANGELES,FA0067509,NEW FLAVORS,CA,90066,,OW0025854,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,NEW FLAVORS,ACTIVE,PR0048350,64,DA7M0FRFG,1,ROUTINE INSPECTION,90066
110239,2015-09-28,EE0000958,11916 S FIGUEROA ST,LOS ANGELES,FA0002898,THREE BEARS BAR-B-Q,CA,90061,,OW0001713,...,RESTAURANT (0-30) SEATS MODERATE RISK,1631,THREE BEARS BAR-B-Q,INACTIVE,PR0023624,65,DAVTNZVG3,1,ROUTINE INSPECTION,90061
120095,2017-12-21,EE0001049,5165 E WHITTIER BLVD,LOS ANGELES,FA0250585,YURI'S AUTHENTIC TACOS AND MEXICAN RESTAURANT,CA,90022-3900,,OW0244672,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,YURI'S AUTHENTIC TACOS AND MEXICAN RESTAURANT,ACTIVE,PR0199596,68,DAH3YQM0T,1,ROUTINE INSPECTION,90022
133946,2016-05-19,EE0001025,112 E 58TH ST,LOS ANGELES,FA0040525,MI POBLANITA,CA,90011,,OW0024045,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,MI POBLANITA,ACTIVE,PR0002318,67,DAHATQ9AI,1,ROUTINE INSPECTION,90011
134037,2017-07-11,EE0000829,888 E DOMINGUEZ ST E,CARSON,FA0007895,CARSON BUFFET,CA,90746,,OW0006281,...,RESTAURANT (151 + ) SEATS HIGH RISK,1641,CARSON BUFFET,INACTIVE,PR0021633,54,DAREI9PD0,1,ROUTINE INSPECTION,90746
138014,2017-03-14,EE0000871,1527 CRENSHAW BLVD,LOS ANGELES,FA0160005,CHINA WOK,CA,90019,,OW0124991,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,CHINA WOK,INACTIVE,PR0148088,64,DA3R20TAF,1,ROUTINE INSPECTION,90019
141493,2017-09-13,EE0000145,11828 SOUTH ST,CERRITOS,FA0069834,ROYAL GARDEN RESTAURANT,CA,90703,,OW0020263,...,RESTAURANT (151 + ) SEATS HIGH RISK,1641,ROYAL GARDEN RESTAURANT,ACTIVE,PR0035712,69,DASVOFOVD,1,ROUTINE INSPECTION,90703
158684,2017-04-28,EE0000747,1017 S GLENDORA AVE,WEST COVINA,FA0166532,FUJIN RAMEN,CA,91790,,OW0129663,...,RESTAURANT (31-60) SEATS HIGH RISK,1635,FUJIN RAMEN,ACTIVE,PR0156849,59,DA0KMBXM7,1,ROUTINE INSPECTION,91790
163110,2017-09-12,EE0000829,940 E DOMINGUEZ ST STE #A,CARSON,FA0044489,PHO KING WAY NOODLES & GRILL,CA,90746,,OW0020993,...,RESTAURANT (31-60) SEATS HIGH RISK,1635,PHO KING WAY NOODLES & GRILL,ACTIVE,PR0045104,55,DAELDAETV,1,ROUTINE INSPECTION,90746
164104,2016-04-13,EE0000720,1606 W 6TH ST,LOS ANGELES,FA0032375,SD COFFEE SHOP,CA,90017,,OW0022596,...,RESTAURANT (0-30) SEATS MODERATE RISK,1631,SD COFFEE SHOP,INACTIVE,PR0033089,68,DASDJZFFG,1,ROUTINE INSPECTION,90017
164694,2017-10-23,EE0000120,1227 S BALDWIN AVE,ARCADIA,FA0158564,NEW FUSION,CA,91007-7511,,OW0123622,...,RESTAURANT (151 + ) SEATS HIGH RISK,1641,NEW FUSION,ACTIVE,PR0146639,69,DAJHHJFYO,1,ROUTINE INSPECTION,91007
165048,2017-09-01,EE0000829,1898 E WILLOW ST,SIGNAL HILL,FA0009834,BLACK BEAR DINER,CA,90755,,OW0004774,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,BLACK BEAR DINER,ACTIVE,PR0044808,60,DATOYOCBL,1,ROUTINE INSPECTION,90755
167459,2015-11-21,EE0001025,6210 S VERMONT AVE,LOS ANGELES,FA0179198,ANTOJITOS Y GARNACHERIA DONA ROSITA,CA,90044-3720,,OW0184788,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,ANTOJITOS Y GARNACHERIA DONA ROSITA,ACTIVE,PR0172758,68,DAYXMYDJH,1,ROUTINE INSPECTION,90044
170995,2017-06-27,EE0000854,705 1/2 S WESTERN AVE,LOS ANGELES,FA0054303,VIP CHINESE RESTAURANT,CA,90005,,OW0036705,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,VIP CHINESE RESTAURANT,INACTIVE,PR0023377,66,DAL0V00KY,1,ROUTINE INSPECTION,90005
172436,2017-10-17,EE0000338,2123 SAWTELLE BLVD,LOS ANGELES,FA0050780,TATSU RAMEN,CA,90025,,OW0025501,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,TATSU RAMEN,ACTIVE,PR0003923,66,DAOKWLHLJ,1,ROUTINE INSPECTION,90025
172705,2017-08-08,EE0000829,675 E UNIVERSITY DR,CARSON,FA0243721,PJ'S GRILL BURGERS & DOGS,CA,90746,,OW0238976,...,RESTAURANT (0-30) SEATS HIGH RISK,1632,PJ'S GRILL BURGERS & DOGS,ACTIVE,PR0191956,65,DANHMDRKA,1,ROUTINE INSPECTION,90746
176987,2017-04-04,EE0000821,301 N GARFIELD AVE STE D,MONTEREY PARK,FA0159362,YUNAN RESTAURANT,CA,91754,,OW0124374,...,RESTAURANT (61-150) SEATS HIGH RISK,1638,YUNAN RESTAURANT,INACTIVE,PR0147425,59,DAYZJZT1T,1,ROUTINE INSPECTION,91754